<?php
declare(strict_types=1);

// Waifuim SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

WaifuimUtility::setRegistrar(function (WaifuimUtility $u): void {
    $u->clean = [WaifuimClean::class, 'call'];
    $u->done = [WaifuimDone::class, 'call'];
    $u->make_error = [WaifuimMakeError::class, 'call'];
    $u->feature_add = [WaifuimFeatureAdd::class, 'call'];
    $u->feature_hook = [WaifuimFeatureHook::class, 'call'];
    $u->feature_init = [WaifuimFeatureInit::class, 'call'];
    $u->fetcher = [WaifuimFetcher::class, 'call'];
    $u->make_fetch_def = [WaifuimMakeFetchDef::class, 'call'];
    $u->make_context = [WaifuimMakeContext::class, 'call'];
    $u->make_options = [WaifuimMakeOptions::class, 'call'];
    $u->make_request = [WaifuimMakeRequest::class, 'call'];
    $u->make_response = [WaifuimMakeResponse::class, 'call'];
    $u->make_result = [WaifuimMakeResult::class, 'call'];
    $u->make_point = [WaifuimMakePoint::class, 'call'];
    $u->make_spec = [WaifuimMakeSpec::class, 'call'];
    $u->make_url = [WaifuimMakeUrl::class, 'call'];
    $u->param = [WaifuimParam::class, 'call'];
    $u->prepare_auth = [WaifuimPrepareAuth::class, 'call'];
    $u->prepare_body = [WaifuimPrepareBody::class, 'call'];
    $u->prepare_headers = [WaifuimPrepareHeaders::class, 'call'];
    $u->prepare_method = [WaifuimPrepareMethod::class, 'call'];
    $u->prepare_params = [WaifuimPrepareParams::class, 'call'];
    $u->prepare_path = [WaifuimPreparePath::class, 'call'];
    $u->prepare_query = [WaifuimPrepareQuery::class, 'call'];
    $u->graphql_body = [WaifuimGraphql::class, 'body'];
    $u->graphql_errors = [WaifuimGraphql::class, 'errors'];
    $u->result_basic = [WaifuimResultBasic::class, 'call'];
    $u->result_body = [WaifuimResultBody::class, 'call'];
    $u->result_headers = [WaifuimResultHeaders::class, 'call'];
    $u->transform_request = [WaifuimTransformRequest::class, 'call'];
    $u->transform_response = [WaifuimTransformResponse::class, 'call'];
});
